# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Notes to a Future Perfect Self
email:
description: > # this means to ignore newlines until "baseurl:"
  the Future Forever
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thefutureforever.com" # the base hostname & protocol for your site
twitter_username: j373my
github_username:  jekyll

# Build settings
markdown: kramdown


# Add this section to your _config.yml
# You may ignore information you already have
# like title, url and such
#####################################

# Podcast Feed Settings

title:          your-site-title
email:          your-podcast-contact-email
description:    "your-podcast-description"
subtitle:       "your-podcast-subtitle"
url:            your-podcast-url
lang:           your-language-code
author:         your-name
copyright:      "&#x2117; &amp; &#xA9; 2015"
